/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JframeUI;

/**
 *
 * @author USER
 */
public class Account extends javax.swing.JFrame {

    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deshbord = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Transactions = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        deposit = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        LoanMenu = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        withdraw = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deshbord.setBackground(new java.awt.Color(51, 51, 51));
        deshbord.setMaximumSize(new java.awt.Dimension(800, 500));
        deshbord.setMinimumSize(new java.awt.Dimension(800, 500));
        deshbord.setPreferredSize(new java.awt.Dimension(800, 500));
        deshbord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FakeBank");
        deshbord.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Available Balance:");
        deshbord.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 50, 213, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("0.00 BDT");
        deshbord.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 76, 213, 22));

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Deposit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        deshbord.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 213, 37));

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Withdraw");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        deshbord.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 203, 213, 37));

        jButton3.setBackground(new java.awt.Color(0, 204, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Loan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        deshbord.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 246, 213, 40));

        jButton4.setBackground(new java.awt.Color(66, 103, 178));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        deshbord.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 471, 213, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DashBoard");
        deshbord.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 116, 213, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Your Card:");
        deshbord.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 312, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        deshbord.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 344, 213, -1));

        getContentPane().add(deshbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 720));

        Transactions.setBackground(new java.awt.Color(255, 255, 255));
        Transactions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.gif"))); // NOI18N
        jLabel5.setText("jLabel5");
        Transactions.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 334, 114));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        Transactions.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, -1, -1));

        jLabel9.setText("Ferdous Bin Hafiz ");
        Transactions.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 138, -1, -1));

        jLabel10.setText("11/11/2000");
        Transactions.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 160, 96, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Transactions:");
        Transactions.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 510, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jLabel12.setText("Date: 11/11/2000");
        Transactions.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, -1));

        jLabel15.setText("- 2000$ add");
        Transactions.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 272, 90, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Fakebank © 2023");
        Transactions.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 703, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jLabel14.setText("Date: 11/11/2000");
        Transactions.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 306, 90, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jLabel16.setText("Date: 11/11/2000");
        Transactions.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 362, 90, -1));

        jLabel17.setText("2000$ add");
        Transactions.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 328, 90, -1));

        jLabel18.setText("2000$ add");
        Transactions.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 396, 90, -1));

        jTabbedPane1.addTab("tab2", Transactions);

        deposit.setBackground(new java.awt.Color(255, 255, 255));
        deposit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.gif"))); // NOI18N
        jLabel20.setText("jLabel5");
        deposit.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 334, 114));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel21.setBorder(new javax.swing.border.MatteBorder(null));
        deposit.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, -1, -1));

        jLabel22.setText("Ferdous Bin Hafiz ");
        deposit.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 138, -1, -1));

        jLabel23.setText("11/11/2000");
        deposit.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 160, 96, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Fakebank © 2023");
        deposit.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 693, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("Deposit Menu");
        deposit.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 211, 165, -1));

        jLabel25.setText("Current Balance: 0.00 BDT");
        deposit.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 261, -1, -1));

        jLabel26.setText("Pending Loan: 0.00 BDT");
        deposit.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 283, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jTextField1.setText("Enter Amount...");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        deposit.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 317, 292, -1));

        jButton5.setBackground(new java.awt.Color(66, 103, 178));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Proceed");
        deposit.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 349, -1, -1));

        jButton6.setText("Back");
        deposit.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 349, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("Last Deposit: ");
        deposit.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jLabel29.setText("Date: 11/11/2000");
        deposit.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 428, 94, -1));

        jLabel30.setText("- 2000 BDT deposit from Mim");
        deposit.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jTabbedPane1.addTab("", deposit);

        LoanMenu.setBackground(new java.awt.Color(255, 255, 255));
        LoanMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.gif"))); // NOI18N
        jLabel42.setText("jLabel5");
        LoanMenu.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 334, 114));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoanMenu.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, -1, -1));

        jLabel44.setText("Ferdous Bin Hafiz ");
        LoanMenu.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 138, -1, -1));

        jLabel45.setText("11/11/2000");
        LoanMenu.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 160, 96, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("Fakebank © 2023");
        LoanMenu.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 703, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel47.setText("Loan Menu");
        LoanMenu.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 211, -1, -1));

        jLabel48.setText("Current Balance: 0.00 BDT");
        LoanMenu.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 261, -1, -1));

        jLabel49.setText("Pending Loan: 0.00 BDT");
        LoanMenu.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 283, -1, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jTextField3.setText("Enter Amount...");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        LoanMenu.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 317, 292, -1));

        jButton9.setBackground(new java.awt.Color(66, 103, 178));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Proceed");
        LoanMenu.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 349, -1, -1));

        jButton10.setText("Back");
        LoanMenu.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 349, -1, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel50.setText("Last Loan: ");
        LoanMenu.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jLabel51.setText("Date: 11/11/2000");
        LoanMenu.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 428, 94, -1));

        jLabel52.setText("- 2000 BDT Loan");
        LoanMenu.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jTabbedPane1.addTab("tab3", LoanMenu);

        withdraw.setBackground(new java.awt.Color(255, 255, 255));
        withdraw.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.gif"))); // NOI18N
        jLabel31.setText("jLabel5");
        withdraw.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 334, 114));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel32.setBorder(new javax.swing.border.MatteBorder(null));
        withdraw.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, -1, -1));

        jLabel33.setText("Ferdous Bin Hafiz ");
        withdraw.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 138, -1, -1));

        jLabel34.setText("11/11/2000");
        withdraw.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 160, 96, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Fakebank © 2023");
        withdraw.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 703, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setText("Withdraw Menu");
        withdraw.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 211, -1, -1));

        jLabel37.setText("Current Balance: 0.00 BDT");
        withdraw.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 261, -1, -1));

        jLabel38.setText("Pending Loan: 0.00 BDT");
        withdraw.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 283, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jTextField2.setText("Enter Amount...");
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        withdraw.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 317, 292, -1));

        jButton7.setBackground(new java.awt.Color(66, 103, 178));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Proceed");
        withdraw.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 349, -1, -1));

        jButton8.setText("Back");
        withdraw.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 349, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel39.setText("Last Withdraw: ");
        withdraw.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jLabel40.setText("Date: 11/11/2000");
        withdraw.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 428, 94, -1));

        jLabel41.setText("- 2000 BDT Withdraw");
        withdraw.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jTabbedPane1.addTab("tab4", withdraw);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -40, 540, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoanMenu;
    private javax.swing.JPanel Transactions;
    private javax.swing.JPanel deposit;
    private javax.swing.JPanel deshbord;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel withdraw;
    // End of variables declaration//GEN-END:variables
}
